# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-10-24 11:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ename', models.CharField(max_length=11, verbose_name='用户名')),
                ('eaddr', models.CharField(max_length=11, verbose_name='email地址')),
            ],
        ),
    ]
